import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Nav from '@/components/Nav';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Trade or Tighten</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className="py-24">
        <div className="max-w-7xl mx-auto">
          <h1 className="font-semibold text-6xl">
            Welcome to Trade or Tighten
          </h1>
        </div>
      </main>

      <footer>
      </footer>
    </div>
  );
};

export default Home;
